name: Fetch Live SharePoint Data

on:
  workflow_dispatch:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      # --- THIS IS THE NEW STEP THAT FIXES THE ERROR ---
      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Fetch and process data from SharePoint
        run: python get_data.py
        env:
          SHAREPOINT_USERNAME: ${{ secrets.SHAREPOINT_USERNAME }}
          SHAREPOINT_PASSWORD: ${{ secrets.SHAREPOINT_PASSWORD }}

      - name: Commit and push if data changed
        uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "Automated update of SharePoint data"
          file_pattern: "data.json"
